import {
  db,
  categoriesTable,
  subcategoriesTable,
  adsTable,
} from "@workspace/db";
import { sql } from "drizzle-orm";

async function main() {
  await db.execute(sql`TRUNCATE TABLE ads, subcategories, categories RESTART IDENTITY CASCADE`);

  const categories = [
    { name: "العقارات", slug: "immobilien", icon: "home", subtitle: "شقق، منازل وأراضٍ", subs: ["شقق للإيجار", "شقق للبيع", "غرف مشتركة", "محلات تجارية"] },
    { name: "الأزياء والجمال", slug: "mode-beauty", icon: "shirt", subtitle: "ملابس، إكسسوارات ومجوهرات", subs: ["ملابس رجالية", "ملابس نسائية", "ملابس أطفال", "أحذية", "حقائب وإكسسوارات", "عطور وعناية"] },
    { name: "السيارات والدراجات", slug: "auto-rad", icon: "car", subtitle: "مركبات وقطع غيار", subs: ["سيارات", "دراجات نارية", "دراجات هوائية", "قطع غيار", "إطارات"] },
    { name: "المنزل والحديقة", slug: "haus-garten", icon: "sofa", subtitle: "أثاث، ديكور وأدوات", subs: ["أثاث غرف نوم", "أثاث صالون", "أدوات مطبخ", "ديكور", "حدائق ونباتات"] },
    { name: "الإلكترونيات", slug: "elektronik", icon: "smartphone", subtitle: "هواتف وأجهزة كمبيوتر", subs: ["هواتف ذكية", "حواسيب محمولة", "تلفزيونات", "ألعاب فيديو", "أجهزة منزلية"] },
    { name: "الوظائف", slug: "jobs", icon: "briefcase", subtitle: "فرص عمل وتدريب", subs: ["دوام كامل", "دوام جزئي", "تدريب مهني", "عمل عن بُعد"] },
    { name: "العائلة والأطفال", slug: "familie", icon: "baby", subtitle: "ألعاب ومستلزمات أطفال", subs: ["عربات أطفال", "ملابس أطفال", "ألعاب", "حضانة"] },
    { name: "الحيوانات الأليفة", slug: "haustiere", icon: "paw-print", subtitle: "حيوانات ومستلزماتها", subs: ["قطط", "كلاب", "طيور", "مستلزمات"] },
    { name: "الترفيه والهوايات", slug: "freizeit", icon: "tent", subtitle: "رياضة، رحلات وفنون", subs: ["رياضة", "موسيقى", "كتب", "كاميرات", "ألعاب لوحية"] },
    { name: "الموسيقى والكتب", slug: "musik-buecher", icon: "book-open", subtitle: "كتب، آلات وأفلام", subs: ["كتب عربية", "كتب ألمانية", "آلات موسيقية", "أفلام"] },
    { name: "تذاكر وفعاليات", slug: "tickets", icon: "ticket", subtitle: "حفلات، رياضة وقطارات", subs: ["حفلات", "مباريات", "تذاكر قطار"] },
    { name: "الخدمات", slug: "dienstleistungen", icon: "wrench", subtitle: "صيانة، تنظيف ورعاية", subs: ["نقل عفش", "تنظيف", "صيانة", "ترجمة", "دروس خصوصية"] },
    { name: "للتبادل والإهداء", slug: "verschenken", icon: "gift", subtitle: "مجاناً ومقايضة", subs: ["مجاناً", "للمقايضة"] },
    { name: "دروس ودورات", slug: "unterricht", icon: "graduation-cap", subtitle: "تعليم لغات ومساعدة دراسية", subs: ["لغة ألمانية", "لغة عربية", "مساعدة مدرسية", "دورات مهنية"] },
    { name: "مساعدة الجوار", slug: "nachbarschaft", icon: "heart-handshake", subtitle: "خدمات قريبة منك", subs: ["مشاوير", "مساعدة كبار السن", "أعمال صغيرة"] },
  ];

  for (const [i, c] of categories.entries()) {
    const [inserted] = await db
      .insert(categoriesTable)
      .values({ name: c.name, slug: c.slug, icon: c.icon, subtitle: c.subtitle, sortOrder: i })
      .returning();
    if (!inserted) continue;
    await db.insert(subcategoriesTable).values(
      c.subs.map((name) => ({ name, categoryId: inserted.id })),
    );
  }

  const cats = await db.select().from(categoriesTable);
  const bySlug = Object.fromEntries(cats.map((c) => [c.slug, c.id]));

  const sampleImage = (q: string, seed: number) =>
    `https://picsum.photos/seed/souq-${seed}/640/640`;

  const ads = [
    {
      title: "آيفون 13 برو 256 جيجا - حالة ممتازة",
      description: "هاتف آيفون 13 برو، لون رمادي فضائي، سعة 256 جيجابايت. استُعمل بحرص شديد، البطارية بحالة 92%. يأتي مع العلبة الأصلية وكابل الشحن. لا توجد خدوش على الشاشة. مناسب للبيع لأنه عندي ترقية للهاتف الأحدث.",
      price: 549,
      priceType: "negotiable",
      type: "offer",
      city: "برلين",
      categoryId: bySlug["elektronik"]!,
      sellerName: "أحمد العلي",
      sellerPhone: "+4915112345678",
      featured: true,
      images: [sampleImage("iphone", 1), sampleImage("iphone-back", 2)],
    },
    {
      title: "كنبة 3 مقاعد إيكيا - رمادي",
      description: "كنبة من إيكيا موديل KIVIK، ثلاث مقاعد، لون رمادي فاتح. مستعملة سنتين فقط، نظيفة جداً وبدون أي بقع. الغطاء قابل للغسل. الأبعاد: 228×95×83 سم. يجب الاستلام من المنزل لصعوبة النقل.",
      price: 220,
      priceType: "fixed",
      type: "offer",
      city: "كولونيا",
      categoryId: bySlug["haus-garten"]!,
      sellerName: "ليلى حسن",
      sellerPhone: "+4915223456789",
      featured: true,
      images: [sampleImage("sofa", 3)],
    },
    {
      title: "فولكس فاجن جولف 2015 - ماشية 120 ألف",
      description: "سيارة فولكس فاجن جولف موديل 2015، محرك 1.4 بنزين، ناقل حركة يدوي. الكيلومتراج 120,000 كم، خدمة منتظمة عند الوكيل، فحص TÜV ساري حتى 2027. لون أبيض، جميع الأوراق سليمة.",
      price: 7800,
      priceType: "negotiable",
      type: "offer",
      city: "فرانكفورت",
      categoryId: bySlug["auto-rad"]!,
      sellerName: "خالد منصور",
      sellerPhone: "+4915334567890",
      featured: true,
      images: [sampleImage("car-vw", 4)],
    },
    {
      title: "شقة غرفتين للإيجار - وسط مدينة هامبورغ",
      description: "شقة جميلة بغرفتين نوم، صالون واسع، مطبخ مجهز بالكامل وحمام. المساحة 65 متر مربع، الطابق الثالث مع مصعد. قريبة من محطة المترو ومن المحلات. تتوفر مع الأثاث أو بدونه.",
      price: 980,
      priceType: "fixed",
      type: "offer",
      city: "هامبورغ",
      categoryId: bySlug["immobilien"]!,
      sellerName: "محمد إبراهيم",
      sellerPhone: "+4915445678901",
      featured: false,
      images: [sampleImage("apartment", 5)],
    },
    {
      title: "دراجة هوائية للأطفال - مقاس 20 إنش",
      description: "دراجة أطفال نظيفة، مناسبة للأعمار من 6 إلى 9 سنوات. لون أزرق، مع عجلات مساعدة قابلة للفك. الفرامل والإطارات بحالة ممتازة. سبب البيع كبر ابني عليها.",
      price: 45,
      priceType: "negotiable",
      type: "offer",
      city: "ميونخ",
      categoryId: bySlug["familie"]!,
      sellerName: "فاطمة الزهراء",
      sellerPhone: "+4915556789012",
      featured: false,
      images: [sampleImage("kids-bike", 6)],
    },
    {
      title: "ملابس أطفال مستعملة - مجاناً",
      description: "كيس كبير من ملابس أطفال أعمار 2-4 سنوات، أولاد. نظيفة ومغسولة، فيها كنزات وبنطلونات وقمصان. للاستلام من المنزل فقط، لا أرسل بالبريد.",
      price: null,
      priceType: "free",
      type: "offer",
      city: "دوسلدورف",
      categoryId: bySlug["verschenken"]!,
      sellerName: "نور الهدى",
      sellerPhone: "+4915667890123",
      featured: false,
      images: [sampleImage("kids-clothes", 7)],
    },
    {
      title: "ماك بوك برو 2021 M1 - 16 جيجا رام",
      description: "ماك بوك برو شاشة 14 إنش، معالج M1 برو، ذاكرة 16 جيجا، تخزين 512 جيجا SSD. مستعمل لأغراض المكتب فقط. الحالة كالجديد، البطارية 96%. مع الشاحن الأصلي.",
      price: 1450,
      priceType: "negotiable",
      type: "offer",
      city: "برلين",
      categoryId: bySlug["elektronik"]!,
      sellerName: "يوسف الرحمن",
      sellerPhone: "+4915778901234",
      featured: true,
      images: [sampleImage("macbook", 8)],
    },
    {
      title: "أبحث عن غرفة مفروشة في برلين",
      description: "طالب جامعي عربي، هادئ وغير مدخن، أبحث عن غرفة مفروشة في شقة مشتركة (WG) في برلين أو ضواحيها. الميزانية حتى 500 يورو شامل الفواتير. متوفر للانتقال خلال شهر.",
      price: 500,
      priceType: "negotiable",
      type: "request",
      city: "برلين",
      categoryId: bySlug["immobilien"]!,
      sellerName: "عمر السيد",
      sellerPhone: "+4915889012345",
      featured: false,
      images: [sampleImage("room-wanted", 9)],
    },
    {
      title: "دروس خصوصية في اللغة الألمانية - أونلاين",
      description: "مدرسة لغة ألمانية معتمدة (مستوى C2)، أقدم دروساً خاصة لجميع المستويات من A1 إلى B2. تحضير لامتحانات Goethe وtelc. الدروس عبر زوم، أربعة دروس بالأسبوع، السعر للساعة الواحدة.",
      price: 25,
      priceType: "fixed",
      type: "offer",
      city: "شتوتغارت",
      categoryId: bySlug["unterricht"]!,
      sellerName: "هند الكيلاني",
      sellerPhone: "+4915990123456",
      featured: true,
      images: [sampleImage("german-class", 10)],
    },
    {
      title: "خدمة نقل عفش - أسعار مناسبة",
      description: "خدمة نقل أثاث داخل وخارج المدينة، فريق عربي محترف، سيارة كبيرة. نضمن سلامة الأثاث ولدينا تأمين. اتصل لمعرفة السعر حسب المسافة.",
      price: 120,
      priceType: "negotiable",
      type: "offer",
      city: "إيسن",
      categoryId: bySlug["dienstleistungen"]!,
      sellerName: "ياسر الحموي",
      sellerPhone: "+4916001234567",
      featured: false,
      images: [sampleImage("moving", 11)],
    },
    {
      title: "تلفزيون سامسونج 55 إنش 4K",
      description: "تلفزيون سامسونج ذكي، شاشة 55 إنش، دقة 4K UHD، مع جهاز التحكم الأصلي. مستعمل سنة واحدة فقط في غرفة الجلوس. السبب الانتقال إلى منزل أصغر.",
      price: 320,
      priceType: "negotiable",
      type: "offer",
      city: "هانوفر",
      categoryId: bySlug["elektronik"]!,
      sellerName: "سامر العبد",
      sellerPhone: "+4916112345678",
      featured: false,
      images: [sampleImage("tv-samsung", 12)],
    },
    {
      title: "جاكيت شتوي رجالي - مقاس L",
      description: "جاكيت شتوي ثقيل، لون أسود، مقاس L. مستعمل شتاء واحد فقط، مقاوم للماء، مع كبيوشن قابل للفصل. مناسب لطقس ألمانيا البارد.",
      price: 40,
      priceType: "fixed",
      type: "offer",
      city: "كولونيا",
      categoryId: bySlug["mode-beauty"]!,
      sellerName: "كريم الشامي",
      sellerPhone: "+4916223456789",
      featured: false,
      images: [sampleImage("jacket", 13)],
    },
    {
      title: "كتب أطفال عربية - مجموعة 20 كتاب",
      description: "مجموعة قصص أطفال باللغة العربية، حالة ممتازة، مناسبة للأعمار 4-8 سنوات. تتضمن قصصاً مصورة وكتب تعليمية. للبيع جملة فقط.",
      price: 30,
      priceType: "fixed",
      type: "offer",
      city: "برلين",
      categoryId: bySlug["musik-buecher"]!,
      sellerName: "ريم الأنصاري",
      sellerPhone: "+4916334567890",
      featured: false,
      images: [sampleImage("books", 14)],
    },
    {
      title: "بلايستيشن 5 + يدّتين + لعبتين",
      description: "جهاز بلايستيشن 5 ديسك، مع يدّتين أصليتين ولعبتين (FIFA 24 وSpider-Man 2). الجهاز بحالة الجديد، استُعمل فقط 6 أشهر. صندوق وأوراق أصلية.",
      price: 480,
      priceType: "negotiable",
      type: "offer",
      city: "ميونخ",
      categoryId: bySlug["elektronik"]!,
      sellerName: "بلال الحاج",
      sellerPhone: "+4916445678901",
      featured: true,
      images: [sampleImage("ps5", 15)],
    },
    {
      title: "طاولة طعام خشبية + 6 كراسي",
      description: "طاولة طعام من الخشب الصلب، تتسع لـ 6 أشخاص، مع 6 كراسي مطابقة. الطاولة بحالة جيدة جداً، فيها أثر استخدام بسيط. للاستلام من المنزل.",
      price: 180,
      priceType: "negotiable",
      type: "offer",
      city: "فرانكفورت",
      categoryId: bySlug["haus-garten"]!,
      sellerName: "وليد العمر",
      sellerPhone: "+4916556789012",
      featured: false,
      images: [sampleImage("table", 16)],
    },
    {
      title: "قطة شيرازي صغيرة - للتبني",
      description: "قطة شيرازي عمرها 4 أشهر، أنثى، مطعمة وصحيحة. أبحث لها عن أسرة محبة. الأطفال يعانون من حساسية لذلك مضطرة للتنازل عنها. رسوم رمزية لتغطية المطاعيم.",
      price: 50,
      priceType: "fixed",
      type: "offer",
      city: "هامبورغ",
      categoryId: bySlug["haustiere"]!,
      sellerName: "سلمى الطيب",
      sellerPhone: "+4916667890123",
      featured: true,
      images: [sampleImage("cat", 17)],
    },
    {
      title: "دراجة هوائية للبالغين - تريك",
      description: "دراجة هوائية ماركة Trek، مقاس 28 إنش، 21 سرعة. مناسبة للرحلات الطويلة وللاستخدام اليومي. مستعملة لمدة سنة، حالة ممتازة، مع قفل وإضاءة LED.",
      price: 220,
      priceType: "negotiable",
      type: "offer",
      city: "كولونيا",
      categoryId: bySlug["auto-rad"]!,
      sellerName: "عبد الله الصالح",
      sellerPhone: "+4916778901234",
      featured: false,
      images: [sampleImage("trek-bike", 18)],
    },
    {
      title: "غسالة بوش 8 كيلو - تعمل بشكل ممتاز",
      description: "غسالة Bosch، سعة 8 كيلو، فئة طاقة A+++. عمرها 3 سنوات، بحالة ممتازة، تعمل بدون أي مشاكل. سبب البيع الانتقال إلى شقة بها غسالة جاهزة.",
      price: 240,
      priceType: "negotiable",
      type: "offer",
      city: "دوسلدورف",
      categoryId: bySlug["elektronik"]!,
      sellerName: "ناصر الديب",
      sellerPhone: "+4916889012345",
      featured: false,
      images: [sampleImage("washer", 19)],
    },
    {
      title: "تذاكر مباراة بايرن ميونخ - 2 تذكرة",
      description: "تذكرتان لمباراة بايرن ميونخ ضد دورتموند، مدرج طويل، السبت القادم. لا أستطيع الحضور بسبب سفر مفاجئ. السعر للتذكرتين معاً.",
      price: 180,
      priceType: "fixed",
      type: "offer",
      city: "ميونخ",
      categoryId: bySlug["tickets"]!,
      sellerName: "حسام المصري",
      sellerPhone: "+4916990123456",
      featured: false,
      images: [sampleImage("football-tickets", 20)],
    },
  ];

  await db.insert(adsTable).values(
    ads.map((a) => ({
      title: a.title,
      description: a.description,
      price: a.price === null ? null : a.price.toString(),
      priceType: a.priceType,
      type: a.type,
      city: a.city,
      images: a.images,
      categoryId: a.categoryId,
      sellerName: a.sellerName,
      sellerPhone: a.sellerPhone,
      featured: a.featured,
    })),
  );

  console.log(`Seeded ${categories.length} categories and ${ads.length} ads.`);
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
