/**
 * Public German city names for staging `cities` rows.
 * Kept in sync with `artifacts/souq/src/lib/german-cities.ts` (not imported to avoid package coupling).
 */
export const STAGING_PUBLIC_DE_CITY_NAMES: string[] = [
  "Berlin",
  "Hamburg",
  "München",
  "Köln",
  "Frankfurt am Main",
  "Stuttgart",
  "Düsseldorf",
  "Leipzig",
  "Dortmund",
  "Essen",
  "Bremen",
  "Dresden",
  "Hannover",
  "Nürnberg",
  "Duisburg",
  "Bochum",
  "Wuppertal",
  "Bielefeld",
  "Bonn",
  "Münster",
  "Karlsruhe",
  "Mannheim",
  "Augsburg",
  "Wiesbaden",
  "Mönchengladbach",
  "Gelsenkirchen",
  "Braunschweig",
  "Kiel",
  "Chemnitz",
  "Aachen",
  "Halle",
  "Magdeburg",
  "Freiburg im Breisgau",
  "Krefeld",
  "Lübeck",
  "Mainz",
  "Erfurt",
  "Oberhausen",
  "Rostock",
  "Kassel",
  "Hagen",
  "Saarbrücken",
  "Hamm",
  "Potsdam",
  "Mülheim an der Ruhr",
  "Ludwigshafen",
  "Oldenburg",
  "Leverkusen",
  "Osnabrück",
  "Solingen",
  "Heidelberg",
  "Herne",
  "Neuss",
  "Darmstadt",
  "Paderborn",
  "Regensburg",
  "Ingolstadt",
  "Würzburg",
  "Fürth",
  "Wolfsburg",
  "Offenbach am Main",
  "Ulm",
  "Heilbronn",
  "Pforzheim",
  "Göttingen",
  "Bottrop",
  "Trier",
  "Recklinghausen",
  "Reutlingen",
  "Bremerhaven",
  "Koblenz",
  "Bergisch Gladbach",
  "Jena",
  "Remscheid",
  "Erlangen",
  "Moers",
  "Siegen",
  "Hildesheim",
  "Salzgitter",
  "Cottbus",
  "Kaiserslautern",
];
