[souq-nginx-limit]
enabled = true
filter = souq-nginx-limit
port = http,https
logpath = /var/log/souq-arab/nginx-api-error.log
maxretry = 60
findtime = 15m
bantime = 20m
banaction = ufw
ignoreip = 127.0.0.1/8 ::1
