import { Router, type IRouter } from "express";
import healthRouter from "./health";
import categoriesRouter from "./categories";
import adsRouter from "./ads";
import aiRouter from "./ai";
import storageRouter from "./storage";
import authRouter from "./auth";
import usersRouter from "./users";
import conversationsRouter from "./conversations";
import reports from "./reports";
import adminRouter from "./admin";
import adminPresenceRouter from "./admin-presence";
import admin2faRouter from "./admin-2fa";
import supportRouter from "./support";
import notificationsRouter from "./notifications";
import pushRouter from "./push";
import accountRouter from "./account";
import observabilityRouter from "./observability";
import adminReportsWorkflowRouter from "./admin-reports-workflow";
import adminVerificationWorkflowRouter from "./admin-verification-workflow";
import adminOperationsRouter from "./admin-operations";
import adminMonitoringRouter from "./admin-monitoring";
import adminJobsRouter from "./admin-jobs";
import adminStaffRouter from "./admin-staff";
import adminNotificationsRouter from "./admin-notifications";
import ordersRouter from "./orders";

const router: IRouter = Router();

router.use(healthRouter);
router.use(observabilityRouter);
router.use(categoriesRouter);
router.use(adsRouter);
router.use(aiRouter);
router.use(storageRouter);
router.use(authRouter);
router.use(adminPresenceRouter);
router.use(usersRouter);
router.use(conversationsRouter);
router.use("/reports", reports);
router.use(adminRouter);
router.use(adminReportsWorkflowRouter);
router.use(adminVerificationWorkflowRouter);
router.use(adminOperationsRouter);
router.use(adminMonitoringRouter);
router.use(adminJobsRouter);
router.use(adminStaffRouter);
router.use(adminNotificationsRouter);
router.use(admin2faRouter);
router.use(supportRouter);
router.use(notificationsRouter);
router.use(pushRouter);
router.use(accountRouter);
router.use(ordersRouter);
export default router;
