import type { Locale } from "@/i18n";

type LabelMap = Record<string, string>;

const EN_LABELS: LabelMap = {
  // Main categories
  "السيارات والدراجات والقوارب": "Cars, Bikes & Boats",
  "العقارات": "Real Estate",
  "المنزل والحديقة": "Home & Garden",
  "الموضة والجمال": "Fashion & Beauty",
  "الإلكترونيات": "Electronics",
  "الحيوانات الأليفة": "Pets",
  "الأسرة والطفل والرضّع": "Family, Kids & Babies",
  "الوظائف": "Jobs",
  "أوقات الفراغ والهوايات والجوار": "Leisure, Hobbies & Community",
  "الموسيقى والأفلام والكتب": "Music, Movies & Books",
  "تذاكر الدخول والتذاكر": "Tickets",
  "الخدمات": "Services",
  "الهدايا والتبادل": "Gifts & Exchange",
  "الدروس والكورسات": "Lessons & Courses",
  "مساعدة الجيران": "Neighborhood Help",

  // Common subcategories / leaves
  "سيارات": "Cars",
  "دراجات نارية": "Motorcycles",
  "دراجات هوائية": "Bicycles",
  "قوارب": "Boats",
  "قطع غيار وإكسسوارات": "Parts & Accessories",
  "شقق": "Apartments",
  "منازل": "Houses",
  "غرف وسكن مشترك": "Rooms & Shared Housing",
  "مكاتب ومحلات": "Offices & Shops",
  "أراضٍ": "Land",
  "رياضية": "Sport",
  "سكوتر": "Scooter",
  "كلاسيكية": "Classic",
  "جبلية": "Mountain",
  "مدينة": "City",
  "طريق": "Road",
  "قوارب صيد": "Fishing Boats",
  "قوارب نزهة": "Leisure Boats",
  "إطارات": "Tires",
  "بطاريات": "Batteries",
  "زيوت": "Oils",
  "أثاث": "Furniture",
  "أجهزة منزلية": "Home Appliances",
  "مستلزمات الحديقة": "Garden Supplies",
  "ديكور": "Decor",
  "غرفة نوم": "Bedroom",
  "صالة": "Living Room",
  "مكتب": "Office",
  "مطبخ": "Kitchen",
  "تدفئة وتبريد": "Heating & Cooling",
  "نباتات": "Plants",
  "أدوات حدائق": "Garden Tools",
  "جلسات خارجية": "Outdoor Seating",
  "لوحات": "Wall Art",
  "سجاد": "Rugs",
  "إضاءة": "Lighting",
  "ملابس نسائية": "Women's Clothing",
  "ملابس رجالية": "Men's Clothing",
  "أحذية وحقائب": "Shoes & Bags",
  "مستحضرات تجميل": "Cosmetics",
  "فساتين": "Dresses",
  "جاكيتات": "Jackets",
  "عبايات": "Abayas",
  "قمصان": "Shirts",
  "بدلات": "Suits",
  "أحذية": "Shoes",
  "حقائب": "Bags",
  "إكسسوارات": "Accessories",
  "عناية بالبشرة": "Skincare",
  "مكياج": "Makeup",
  "عطور": "Perfumes",
  "الهواتف المحمولة": "Mobile Phones",
  "أجهزة كمبيوتر": "Computers",
  "أجهزة لوحية": "Tablets",
  "ألعاب فيديو": "Video Games",
  "إكسسوارات إلكترونية": "Electronic Accessories",
  "آبل": "Apple",
  "أبل": "Apple",
  "سامسونج": "Samsung",
  "شاومي": "Xiaomi",
  "هواوي": "Huawei",
  "نوكيا": "Nokia",
  "سوني": "Sony",
  "جوجل": "Google",
  "لابتوب": "Laptop",
  "كمبيوتر مكتبي": "Desktop Computer",
  "شاشات": "Monitors",
  "آيباد": "iPad",
  "سامسونج تاب": "Samsung Tab",
  "سماعات": "Headphones",
  "شواحن": "Chargers",
  "ساعات ذكية": "Smart Watches",
  "كلاب": "Dogs",
  "قطط": "Cats",
  "طيور": "Birds",
  "أسماك": "Fish",
  "تبنّي": "Adoption",
  "مستلزمات": "Supplies",
  "تدريب": "Training",
  "عناية": "Care",
  "ببغاوات": "Parrots",
  "كناري": "Canaries",
  "أقفاص": "Cages",
  "أحواض": "Aquariums",
  "أسماك زينة": "Ornamental Fish",
  "عربات أطفال": "Strollers",
  "ملابس أطفال": "Kids Clothing",
  "ألعاب": "Toys",
  "أثاث أطفال": "Kids Furniture",
  "عربة مفردة": "Single Stroller",
  "عربة مزدوجة": "Double Stroller",
  "حديثو الولادة": "Newborn",
  "أطفال": "Children",
  "مراهقون": "Teenagers",
  "تعليمية": "Educational",
  "إلكترونية": "Electronic",
  "خارجية": "Outdoor",
  "أسرة": "Beds",
  "خزائن": "Wardrobes",
  "مكاتب دراسة": "Study Desks",
  "دوام كامل": "Full-time",
  "دوام جزئي": "Part-time",
  "تدريب عملي": "Internship",
  "عمل حر": "Freelance",
  "تقني": "Technical",
  "مبيعات": "Sales",
  "إدارة": "Management",
  "مطاعم": "Restaurants",
  "توصيل": "Delivery",
  "خدمات": "Services",
  "طلاب": "Students",
  "خريجون": "Graduates",
  "تصميم": "Design",
  "برمجة": "Programming",
  "كتابة": "Writing",
  "رياضة ولياقة": "Sports & Fitness",
  "هوايات يدوية": "Handmade Hobbies",
  "فعاليات الجوار": "Community Events",
  "رحلات وتخييم": "Trips & Camping",
  "معدات رياضية": "Sports Equipment",
  "ملابس رياضية": "Sportswear",
  "رسم": "Drawing",
  "خياطة": "Sewing",
  "أعمال خشبية": "Woodwork",
  "لقاءات": "Meetups",
  "أنشطة عائلية": "Family Activities",
  "خيام": "Tents",
  "معدات طبخ": "Cooking Equipment",
  "آلات موسيقية": "Musical Instruments",
  "أفلام": "Movies",
  "كتب": "Books",
  "موسيقى": "Music",
  "غيتار": "Guitar",
  "بيانو": "Piano",
  "آلات إيقاعية": "Percussion Instruments",
  "ملصقات": "Posters",
  "مقتنيات": "Collectibles",
  "روايات": "Novels",
  "حفلات": "Concerts",
  "رياضة": "Sports",
  "مسرح وسينما": "Theater & Cinema",
  "مواصلات وسفر": "Transport & Travel",
  "موسيقية": "Music",
  "كوميدية": "Comedy",
  "مهرجانات": "Festivals",
  "كرة قدم": "Football",
  "كرة سلة": "Basketball",
  "مسرح": "Theater",
  "سينما": "Cinema",
  "قطارات": "Trains",
  "طيران": "Flights",
  "حافلات": "Buses",
  "صيانة وإصلاح": "Maintenance & Repair",
  "تنظيف": "Cleaning",
  "نقل وتوصيل": "Moving & Delivery",
  "تصميم وتسويق": "Design & Marketing",
  "سباكة": "Plumbing",
  "هواتف": "Phones",
  "مكاتب": "Offices",
  "نقل أثاث": "Furniture Moving",
  "توصيل محلي": "Local Delivery",
  "تصميم جرافيك": "Graphic Design",
  "تسويق رقمي": "Digital Marketing",
  "هدايا مجانية": "Free Gifts",
  "تبادل إلكترونيات": "Electronics Exchange",
  "تبادل أثاث": "Furniture Exchange",
  "تبادل خدمات": "Services Exchange",
  "منزلية": "Home",
  "ملابس": "Clothing",
  "تعليم مقابل تعليم": "Tutoring for Tutoring",
  "نقل مقابل صيانة": "Moving for Maintenance",
  "لغات": "Languages",
  "تقنية": "Technology",
  "دروس مدرسية": "School Lessons",
  "دروس موسيقى": "Music Lessons",
  "ألمانية": "German",
  "إنجليزية": "English",
  "عربية": "Arabic",
  "تحليل بيانات": "Data Analysis",
  "رياضيات": "Mathematics",
  "علوم": "Science",
  "غناء": "Singing",
  "مساعدة منزلية": "Home Help",
  "رعاية كبار السن": "Elderly Care",
  "رعاية أطفال": "Child Care",
  "مساعدة تقنية": "Tech Help",
  "تسوق": "Shopping",
  "تنظيف خفيف": "Light Cleaning",
  "أعمال بسيطة": "Simple Tasks",
  "مرافقة": "Companionship",
  "تسوق أدوية": "Medication Pickup",
  "ساعات مسائية": "Evening Hours",
  "عطلات نهاية الأسبوع": "Weekends",
  "إعداد هواتف": "Phone Setup",
  "حل مشاكل الكمبيوتر": "Computer Troubleshooting",

  // Dynamic field labels and common options
  "الشركة": "Brand",
  "الموديل": "Model",
  "سنة الصنع": "Year",
  "الكيلومترات": "Mileage",
  "نوع الوقود": "Fuel Type",
  "ناقل الحركة": "Transmission",
  "نوع العقار": "Property Type",
  "المساحة": "Area",
  "عدد الغرف": "Rooms",
  "الإيجار/البيع": "Rent/Sale",
  "اللون": "Color",
  "الحالة": "Condition",
  "السعة التخزينية": "Storage",
  "الجهاز والملحقات": "Device & Accessories",
  "أخرى": "Other",
  "جديد": "New",
  "مثل الجديد": "Like new",
  "جيد جداً": "Very good",
  "جيد جدا": "Very good",
  "جيد": "Good",
  "مقبول": "Fair",
  "مستعمل": "Used",
  "يحتاج صيانة": "Needs maintenance",
  "أسود": "Black",
  "أبيض": "White",
  "فضي": "Silver",
  "ذهبي": "Gold",
  "أزرق": "Blue",
  "أحمر": "Red",
  "أخضر": "Green",
  "بنفسجي": "Purple",
  "وردي": "Pink",
  "رمادي": "Gray",
  "الجهاز فقط": "Device only",
  "مع الشاحن": "With charger",
  "مع العلبة": "With box",
  "مع الشاحن والعلبة": "With charger and box",
  "مع سماعات": "With earphones",
  "كامل الملحقات": "Full accessories",
  "بنزين": "Petrol",
  "ديزل": "Diesel",
  "كهرباء": "Electric",
  "هايبرد": "Hybrid",
  "غاز": "Gas",
  "أوتوماتيك": "Automatic",
  "يدوي": "Manual",
  "نصف أوتوماتيك": "Semi-automatic",
  "بيع": "Sale",
  "إيجار": "Rent",
  "صغير": "Compact",
  "سيدان": "Sedan",
  "كوبيه": "Coupe",
  "هاتشباك": "Hatchback",
  "فان": "Van",
  "2025+": "2025+",
  "2020-2024": "2020-2024",
  "2015-2019": "2015-2019",
  "2010-2014": "2010-2014",
  "2005-2009": "2005-2009",
  "2000-2004": "2000-2004",
  "أقدم": "Older",
  "أقل من 50,000": "Less than 50,000",
  "50,000 - 100,000": "50,000 - 100,000",
  "100,000 - 150,000": "100,000 - 150,000",
  "150,000 - 200,000": "150,000 - 200,000",
  "200,000+": "200,000+",
  "شقة": "Apartment",
  "استوديو": "Studio",
  "دوبلكس": "Duplex",
  "بنتهاوس": "Penthouse",
  "أقل من 50 م²": "Less than 50 m²",
  "50-80 م²": "50-80 m²",
  "80-120 م²": "80-120 m²",
  "120-180 م²": "120-180 m²",
  "أكثر من 180 م²": "More than 180 m²",
  "منزل مستقل": "Detached House",
  "تاون هاوس": "Townhouse",
  "فيلا": "Villa",
  "غرفة مفردة": "Single Room",
  "غرفة مزدوجة": "Double Room",
  "محل تجاري": "Commercial Shop",
  "مخزن": "Storage",
  "سكنية": "Residential",
  "زراعية": "Agricultural",
  "استثمارية": "Investment",
};

const DE_LABELS: LabelMap = {
  "السيارات والدراجات والقوارب": "Autos, Motorräder & Boote",
  "العقارات": "Immobilien",
  "المنزل والحديقة": "Haus & Garten",
  "الموضة والجمال": "Mode & Schönheit",
  "الإلكترونيات": "Elektronik",
  "الحيوانات الأليفة": "Haustiere",
  "الأسرة والطفل والرضّع": "Familie, Kinder & Babys",
  "الوظائف": "Jobs",
  "أوقات الفراغ والهوايات والجوار": "Freizeit, Hobbys & Nachbarschaft",
  "الموسيقى والأفلام والكتب": "Musik, Filme & Bücher",
  "تذاكر الدخول والتذاكر": "Tickets",
  "الهدايا والتبادل": "Geschenke & Tausch",
  "الدروس والكورسات": "Unterricht & Kurse",
  "مساعدة الجيران": "Nachbarschaftshilfe",
  "سيارات": "Autos",
  "دراجات نارية": "Motorräder",
  "دراجات هوائية": "Fahrräder",
  "قوارب": "Boote",
  "قطع غيار وإكسسوارات": "Ersatzteile & Zubehör",
  "شقق": "Wohnungen",
  "منازل": "Häuser",
  "غرف وسكن مشترك": "Zimmer & WG",
  "مكاتب ومحلات": "Büros & Geschäfte",
  "أراضٍ": "Grundstücke",
  "رياضية": "Sport",
  "سكوتر": "Roller",
  "كلاسيكية": "Klassisch",
  "جبلية": "Mountainbike",
  "مدينة": "Stadt",
  "طريق": "Straße",
  "قوارب صيد": "Angelboote",
  "قوارب نزهة": "Freizeitboote",
  "إطارات": "Reifen",
  "بطاريات": "Batterien",
  "زيوت": "Öle",
  "الهواتف المحمولة": "Handys",
  "أجهزة كمبيوتر": "Computer",
  "أجهزة لوحية": "Tablets",
  "ألعاب فيديو": "Videospiele",
  "أثاث": "Möbel",
  "أجهزة منزلية": "Haushaltsgeräte",
  "مستلزمات الحديقة": "Gartenzubehör",
  "ديكور": "Deko",
  "غرفة نوم": "Schlafzimmer",
  "صالة": "Wohnzimmer",
  "مكتب": "Büro",
  "مطبخ": "Küche",
  "تدفئة وتبريد": "Heizung & Kühlung",
  "نباتات": "Pflanzen",
  "أدوات حدائق": "Gartengeräte",
  "جلسات خارجية": "Außensitzmöbel",
  "لوحات": "Wandbilder",
  "سجاد": "Teppiche",
  "إضاءة": "Beleuchtung",
  "ملابس نسائية": "Damenkleidung",
  "ملابس رجالية": "Herrenkleidung",
  "أحذية وحقائب": "Schuhe & Taschen",
  "مستحضرات تجميل": "Kosmetik",
  "فساتين": "Kleider",
  "جاكيتات": "Jacken",
  "عبايات": "Abayas",
  "قمصان": "Hemden",
  "بدلات": "Anzüge",
  "أحذية": "Schuhe",
  "حقائب": "Taschen",
  "إكسسوارات": "Accessoires",
  "عناية بالبشرة": "Hautpflege",
  "مكياج": "Make-up",
  "عطور": "Parfüms",
  "آبل": "Apple",
  "أبل": "Apple",
  "سامسونج": "Samsung",
  "شاومي": "Xiaomi",
  "هواوي": "Huawei",
  "نوكيا": "Nokia",
  "سوني": "Sony",
  "جوجل": "Google",
  "لابتوب": "Laptop",
  "كمبيوتر مكتبي": "Desktop-PC",
  "شاشات": "Monitore",
  "آيباد": "iPad",
  "سامسونج تاب": "Samsung Tab",
  "إكسسوارات إلكترونية": "Elektronikzubehör",
  "سماعات": "Kopfhörer",
  "شواحن": "Ladegeräte",
  "ساعات ذكية": "Smartwatches",
  "كلاب": "Hunde",
  "قطط": "Katzen",
  "طيور": "Vögel",
  "أسماك": "Fische",
  "تبنّي": "Adoption",
  "مستلزمات": "Zubehör",
  "تدريب": "Training",
  "عناية": "Pflege",
  "ببغاوات": "Papageien",
  "كناري": "Kanarienvögel",
  "أقفاص": "Käfige",
  "أحواض": "Aquarien",
  "أسماك زينة": "Zierfische",
  "عربات أطفال": "Kinderwagen",
  "ملابس أطفال": "Kinderkleidung",
  "ألعاب": "Spielzeug",
  "أثاث أطفال": "Kindermöbel",
  "عربة مفردة": "Einzelkinderwagen",
  "عربة مزدوجة": "Doppelkinderwagen",
  "حديثو الولادة": "Neugeborene",
  "أطفال": "Kinder",
  "مراهقون": "Jugendliche",
  "تعليمية": "Lehrreich",
  "إلكترونية": "Elektronisch",
  "خارجية": "Outdoor",
  "أسرة": "Betten",
  "خزائن": "Schränke",
  "مكاتب دراسة": "Schreibtische",
  "دوام كامل": "Vollzeit",
  "دوام جزئي": "Teilzeit",
  "تدريب عملي": "Praktikum",
  "عمل حر": "Freiberuflich",
  "تقني": "Technisch",
  "مبيعات": "Vertrieb",
  "إدارة": "Management",
  "مطاعم": "Restaurants",
  "توصيل": "Lieferung",
  "خدمات": "Dienste",
  "طلاب": "Studierende",
  "خريجون": "Absolventen",
  "تصميم": "Design",
  "برمجة": "Programmierung",
  "كتابة": "Schreiben",
  "رياضة ولياقة": "Sport & Fitness",
  "هوايات يدوية": "Handwerkliche Hobbys",
  "فعاليات الجوار": "Nachbarschaftsevents",
  "رحلات وتخييم": "Reisen & Camping",
  "معدات رياضية": "Sportausrüstung",
  "ملابس رياضية": "Sportkleidung",
  "رسم": "Zeichnen",
  "خياطة": "Nähen",
  "أعمال خشبية": "Holzarbeiten",
  "لقاءات": "Treffen",
  "أنشطة عائلية": "Familienaktivitäten",
  "خيام": "Zelte",
  "معدات طبخ": "Kochausrüstung",
  "آلات موسيقية": "Musikinstrumente",
  "أفلام": "Filme",
  "كتب": "Bücher",
  "موسيقى": "Musik",
  "غيتار": "Gitarre",
  "بيانو": "Klavier",
  "آلات إيقاعية": "Schlaginstrumente",
  "ملصقات": "Poster",
  "مقتنيات": "Sammlerstücke",
  "روايات": "Romane",
  "حفلات": "Konzerte",
  "رياضة": "Sport",
  "مسرح وسينما": "Theater & Kino",
  "مواصلات وسفر": "Verkehr & Reisen",
  "موسيقية": "Musikalisch",
  "كوميدية": "Comedy",
  "مهرجانات": "Festivals",
  "كرة قدم": "Fußball",
  "كرة سلة": "Basketball",
  "مسرح": "Theater",
  "سينما": "Kino",
  "قطارات": "Züge",
  "طيران": "Flüge",
  "حافلات": "Busse",
  "الخدمات": "Dienstleistungen",
  "صيانة وإصلاح": "Wartung & Reparatur",
  "تنظيف": "Reinigung",
  "نقل وتوصيل": "Umzug & Lieferung",
  "تصميم وتسويق": "Design & Marketing",
  "سباكة": "Sanitär",
  "هواتف": "Telefone",
  "مكاتب": "Büros",
  "نقل أثاث": "Möbeltransport",
  "توصيل محلي": "Lokale Lieferung",
  "تصميم جرافيك": "Grafikdesign",
  "تسويق رقمي": "Digitales Marketing",
  "هدايا مجانية": "Kostenlose Geschenke",
  "تبادل إلكترونيات": "Elektroniktausch",
  "تبادل أثاث": "Möbeltausch",
  "تبادل خدمات": "Dienstleistungstausch",
  "منزلية": "Haushalt",
  "ملابس": "Kleidung",
  "تعليم مقابل تعليم": "Unterricht gegen Unterricht",
  "نقل مقابل صيانة": "Umzug gegen Wartung",
  "لغات": "Sprachen",
  "تقنية": "Technik",
  "دروس مدرسية": "Schulunterricht",
  "دروس موسيقى": "Musikunterricht",
  "ألمانية": "Deutsch",
  "إنجليزية": "Englisch",
  "عربية": "Arabisch",
  "تحليل بيانات": "Datenanalyse",
  "رياضيات": "Mathematik",
  "علوم": "Naturwissenschaften",
  "غناء": "Gesang",
  "مساعدة منزلية": "Haushaltshilfe",
  "رعاية كبار السن": "Seniorenbetreuung",
  "رعاية أطفال": "Kinderbetreuung",
  "مساعدة تقنية": "Technikhilfe",
  "تسوق": "Einkaufen",
  "تنظيف خفيف": "Leichte Reinigung",
  "أعمال بسيطة": "Einfache Aufgaben",
  "مرافقة": "Begleitung",
  "تسوق أدوية": "Medikamentenbesorgung",
  "ساعات مسائية": "Abendstunden",
  "عطلات نهاية الأسبوع": "Wochenenden",
  "إعداد هواتف": "Handy-Einrichtung",
  "حل مشاكل الكمبيوتر": "Computerprobleme lösen",
  "الشركة": "Marke",
  "الموديل": "Modell",
  "سنة الصنع": "Baujahr",
  "الكيلومترات": "Kilometerstand",
  "نوع الوقود": "Kraftstoffart",
  "ناقل الحركة": "Getriebe",
  "نوع العقار": "Objektart",
  "المساحة": "Fläche",
  "عدد الغرف": "Zimmer",
  "الإيجار/البيع": "Miete/Verkauf",
  "اللون": "Farbe",
  "الحالة": "Zustand",
  "السعة التخزينية": "Speicher",
  "الجهاز والملحقات": "Gerät & Zubehör",
  "أخرى": "Andere",
  "جديد": "Neu",
  "مثل الجديد": "Wie neu",
  "جيد جداً": "Sehr gut",
  "جيد جدا": "Sehr gut",
  "جيد": "Gut",
  "مقبول": "Akzeptabel",
  "مستعمل": "Gebraucht",
  "يحتاج صيانة": "Wartung nötig",
  "أسود": "Schwarz",
  "أبيض": "Weiß",
  "فضي": "Silber",
  "ذهبي": "Gold",
  "أزرق": "Blau",
  "أحمر": "Rot",
  "أخضر": "Grün",
  "بنفسجي": "Lila",
  "وردي": "Rosa",
  "رمادي": "Grau",
  "الجهاز فقط": "Nur Gerät",
  "مع الشاحن": "Mit Ladegerät",
  "مع العلبة": "Mit Verpackung",
  "مع الشاحن والعلبة": "Mit Ladegerät und Verpackung",
  "مع سماعات": "Mit Kopfhörern",
  "كامل الملحقات": "Vollständiges Zubehör",
  "بنزين": "Benzin",
  "ديزل": "Diesel",
  "كهرباء": "Elektro",
  "هايبرد": "Hybrid",
  "غاز": "Gas",
  "أوتوماتيك": "Automatik",
  "يدوي": "Manuell",
  "نصف أوتوماتيك": "Halbautomatik",
  "بيع": "Verkauf",
  "إيجار": "Miete",
  "صغير": "Kompakt",
  "سيدان": "Limousine",
  "كوبيه": "Coupé",
  "هاتشباك": "Kompaktklasse",
  "فان": "Van",
  "2025+": "2025+",
  "2020-2024": "2020-2024",
  "2015-2019": "2015-2019",
  "2010-2014": "2010-2014",
  "2005-2009": "2005-2009",
  "2000-2004": "2000-2004",
  "أقدم": "Älter",
  "أقل من 50,000": "Unter 50.000",
  "50,000 - 100,000": "50.000 - 100.000",
  "100,000 - 150,000": "100.000 - 150.000",
  "150,000 - 200,000": "150.000 - 200.000",
  "200,000+": "200.000+",
  "شقة": "Wohnung",
  "استوديو": "Studio",
  "دوبلكس": "Duplex",
  "بنتهاوس": "Penthouse",
  "أقل من 50 م²": "Unter 50 m²",
  "50-80 م²": "50-80 m²",
  "80-120 م²": "80-120 m²",
  "120-180 م²": "120-180 m²",
  "أكثر من 180 م²": "Über 180 m²",
  "منزل مستقل": "Einfamilienhaus",
  "تاون هاوس": "Reihenhaus",
  "فيلا": "Villa",
  "غرفة مفردة": "Einzelzimmer",
  "غرفة مزدوجة": "Doppelzimmer",
  "محل تجاري": "Ladenlokal",
  "مخزن": "Lager",
  "سكنية": "Wohngebiet",
  "زراعية": "Landwirtschaftlich",
  "استثمارية": "Investition",
};

const MAP_BY_LOCALE: Record<Locale, LabelMap> = {
  ar: {},
  en: EN_LABELS,
  de: DE_LABELS,
};

const NON_ARABIC_FALLBACK_BY_LOCALE: Record<Exclude<Locale, "ar">, string> = {
  en: "Category",
  de: "Kategorie",
};

const ARABIC_CHAR_RE = /[\u0600-\u06FF]/;

export function getCreateAdTaxonomyLabel(locale: Locale, canonicalLabel: string): string {
  const translated = MAP_BY_LOCALE[locale]?.[canonicalLabel];
  if (translated && translated.trim().length > 0) return translated;
  if (locale !== "ar" && ARABIC_CHAR_RE.test(canonicalLabel)) {
    return NON_ARABIC_FALLBACK_BY_LOCALE[locale];
  }
  return canonicalLabel;
}
