/**
 * P8-1F — Admin dashboard KPI contracts (single source of truth).
 * Docs: docs/architecture/P08-dashboard-contracts.md
 */

export type DashboardSurface = "main" | "analytics" | "operations" | "monitoring";

export type DashboardContract = {
  id: string;
  dashboard: DashboardSurface;
  name: string;
  api: string;
  responsePath: string;
  source: string;
  meaning: string;
  calculation: string;
  loadingState: string;
  errorState: string;
  emptyState?: string;
  i18nLabelKey?: string;
  rbac?: string;
  placeholder?: boolean;
};

export const DASHBOARD_CONTRACTS: DashboardContract[] = [
  // ── Main / NOC — GET /api/admin/dashboard ─────────────────────────────
  {
    id: "noc.executive.today.new_users",
    dashboard: "main",
    name: "New users today",
    api: "GET /api/admin/dashboard",
    responsePath: "noc.executiveHeader.today.newUsers",
    source: "PostgreSQL users.created_at >= startOfToday (server local TZ)",
    meaning: "User registrations since midnight (server clock)",
    calculation: "COUNT(users) WHERE created_at >= today 00:00",
    loadingState: "DashboardSkeleton on /admin until first dashboard response",
    errorState: "AdminErrorState + retry on /admin",
    i18nLabelKey: "p8.admin.executive.today_new_users",
    rbac: "dashboard.operations | dashboard.moderation",
  },
  {
    id: "noc.executive.today.new_ads",
    dashboard: "main",
    name: "New approved ads today",
    api: "GET /api/admin/dashboard",
    responsePath: "noc.executiveHeader.today.newAds",
    source: "PostgreSQL ads.status=approved AND ads.created_at >= startOfToday",
    meaning: "Ads published (approved) today",
    calculation: "COUNT(ads) WHERE status='approved' AND created_at >= today",
    loadingState: "DashboardSkeleton",
    errorState: "AdminErrorState + retry",
    i18nLabelKey: "p8.admin.executive.today_new_ads",
    rbac: "dashboard.operations | dashboard.moderation",
  },
  {
    id: "noc.executive.today.new_reports",
    dashboard: "main",
    name: "New reports today (open/pending)",
    api: "GET /api/admin/dashboard",
    responsePath: "noc.executiveHeader.today.newReports",
    source: "PostgreSQL reports WHERE status IN ('open','pending') — note: differs from open queue count",
    meaning: "Reports in open or pending status (not filtered by created_at for this field in route; see calculation in admin-noc-snapshot params)",
    calculation: "Passed as newReportsToday from dashboard route: COUNT(reports) status open|pending",
    loadingState: "DashboardSkeleton",
    errorState: "AdminErrorState + retry",
    i18nLabelKey: "p8.admin.executive.today_new_reports",
    rbac: "dashboard.operations | dashboard.moderation",
  },
  {
    id: "noc.executive.today.new_support",
    dashboard: "main",
    name: "New support tickets today",
    api: "GET /api/admin/dashboard",
    responsePath: "noc.executiveHeader.today.newSupport",
    source: "PostgreSQL support_tickets.created_at >= startOfToday",
    meaning: "Support tickets created today (any status)",
    calculation: "COUNT(support_tickets) WHERE created_at >= today (computed in admin-noc-snapshot)",
    loadingState: "DashboardSkeleton",
    errorState: "AdminErrorState + retry",
    i18nLabelKey: "p8.admin.executive.today_new_support",
    rbac: "dashboard.operations | dashboard.moderation",
  },
  {
    id: "noc.executive.intervention_count",
    dashboard: "main",
    name: "Intervention count",
    api: "GET /api/admin/dashboard",
    responsePath: "noc.executiveHeader.interventionCount",
    source: "Derived from needsActionNow items",
    meaning: "Needs-action cards with count>0 and severity warning|critical",
    calculation: "needsActionNow.filter(dataAvailable && count>0 && severity!=='info').length",
    loadingState: "DashboardSkeleton",
    errorState: "AdminErrorState + retry",
    i18nLabelKey: "p8.admin.executive.intervention",
    rbac: "dashboard.operations | dashboard.moderation",
  },
  {
    id: "noc.user.online_now",
    dashboard: "main",
    name: "Online now",
    api: "GET /api/admin/active-app-users-count",
    responsePath: "count (fallback: noc.userIntelligence.onlineNow)",
    source: "In-memory WebSocket map (countUsersWithOpenChatSockets) — P16 at multi-replica scale",
    meaning: "Users with an open app WebSocket connection on this API instance",
    calculation: "Unique user IDs in WS connection map; polled every 45s on dashboard",
    loadingState: "Shows previous count (keepPreviousData) or NOC fallback 0",
    errorState: "Falls back to noc.userIntelligence.onlineNow from dashboard payload",
    i18nLabelKey: "p8.admin.noc.metric.online_now",
    rbac: "system permission required for live poll; others see NOC snapshot value",
  },
  {
    id: "noc.user.active_5m",
    dashboard: "main",
    name: "Active last 5 minutes",
    api: "GET /api/admin/dashboard",
    responsePath: "noc.userIntelligence.activeLast5Minutes",
    source: "PostgreSQL users.last_seen_at >= now()-5m",
    meaning: "Users with last_seen_at within 5 minutes",
    calculation: "COUNT(users) WHERE last_seen_at >= fiveMinutesAgo",
    loadingState: "DashboardSkeleton",
    errorState: "NOC load error banner if noc incomplete",
    i18nLabelKey: "p8.admin.noc.metric.active_5m",
    rbac: "dashboard.operations | dashboard.moderation",
  },
  {
    id: "noc.user.active_today",
    dashboard: "main",
    name: "Active today",
    api: "GET /api/admin/dashboard",
    responsePath: "noc.userIntelligence.activeToday",
    source: "PostgreSQL users.last_seen_at >= startOfToday",
    meaning: "Users active since midnight (last_seen_at)",
    calculation: "COUNT(users) WHERE last_seen_at >= today",
    loadingState: "DashboardSkeleton",
    errorState: "NOC load error banner",
    i18nLabelKey: "p8.admin.noc.metric.active_today",
    rbac: "dashboard.operations | dashboard.moderation",
  },
  {
    id: "noc.user.new_users_today",
    dashboard: "main",
    name: "New users today (intelligence row)",
    api: "GET /api/admin/dashboard",
    responsePath: "noc.userIntelligence.newUsersToday",
    source: "Same as noc.executive.today.new_users",
    meaning: "Duplicate surface of new registrations today",
    calculation: "params.newUsersToday from dashboard route",
    loadingState: "DashboardSkeleton",
    errorState: "NOC load error banner",
    i18nLabelKey: "p8.admin.noc.metric.new_users_today",
    rbac: "dashboard.operations | dashboard.moderation",
  },
  {
    id: "noc.user.blocked_users",
    dashboard: "main",
    name: "Blocked users",
    api: "GET /api/admin/dashboard",
    responsePath: "noc.userIntelligence.blockedUsers",
    source: "PostgreSQL users.is_banned=true",
    meaning: "Banned user accounts",
    calculation: "COUNT(users) WHERE is_banned",
    loadingState: "DashboardSkeleton",
    errorState: "NOC load error banner",
    i18nLabelKey: "p8.admin.noc.metric.blocked_users",
    rbac: "dashboard.operations | dashboard.moderation",
  },
  {
    id: "noc.user.pending_verification_email",
    dashboard: "main",
    name: "Unverified email accounts",
    api: "GET /api/admin/dashboard",
    responsePath: "noc.userIntelligence.pendingVerification",
    source: "PostgreSQL users.email_verified=false",
    meaning: "Users who have not verified email — NOT the verification workflow queue",
    calculation: "COUNT(users) WHERE email_verified=false",
    loadingState: "DashboardSkeleton",
    errorState: "NOC load error banner",
    i18nLabelKey: "p8.admin.noc.metric.pending_verification",
    rbac: "dashboard.operations | dashboard.moderation",
  },
  {
    id: "noc.priority.verification_queue",
    dashboard: "main",
    name: "Verification workflow queue",
    api: "GET /api/admin/dashboard",
    responsePath: "noc.priorityItems[key=verification_queue].count",
    source: "countOpenVerificationRequests() — verification_requests table",
    meaning: "Open identity/seller verification requests awaiting staff action",
    calculation: "Workflow open count — distinct from unverified email metric",
    loadingState: "DashboardSkeleton",
    errorState: "NOC load error banner",
    i18nLabelKey: "p8.admin.priority.verification_queue",
    rbac: "dashboard.operations | dashboard.moderation",
  },
  {
    id: "noc.needs_action.pending_ads",
    dashboard: "main",
    name: "Pending ads review",
    api: "GET /api/admin/dashboard",
    responsePath: "noc.needsActionNow[key=pending_ads].count",
    source: "PostgreSQL ads.status='pending'",
    meaning: "Ads awaiting moderation",
    calculation: "COUNT(ads) WHERE status='pending'",
    loadingState: "DashboardSkeleton",
    errorState: "NOC load error banner",
    i18nLabelKey: "p8.admin.needs_action.pending_ads",
    rbac: "dashboard.operations | dashboard.moderation",
  },
  {
    id: "noc.needs_action.open_reports",
    dashboard: "main",
    name: "Open reports",
    api: "GET /api/admin/dashboard",
    responsePath: "noc.needsActionNow[key=open_reports].count",
    source: "PostgreSQL reports.status IN open|under_review|pending|in_review",
    meaning: "Reports not resolved/rejected",
    calculation: "COUNT(reports) WHERE status IN OPEN_REPORT_STATUSES",
    loadingState: "DashboardSkeleton",
    errorState: "NOC load error banner",
    i18nLabelKey: "p8.admin.needs_action.open_reports",
    rbac: "dashboard.operations | dashboard.moderation",
  },
  {
    id: "noc.needs_action.open_support",
    dashboard: "main",
    name: "Open support tickets",
    api: "GET /api/admin/dashboard",
    responsePath: "noc.needsActionNow[key=open_support].count",
    source: "PostgreSQL support_tickets.status IN ('open','pending')",
    meaning: "Support tickets needing staff attention",
    calculation: "COUNT(support_tickets) WHERE status IN OPEN_SUPPORT_STATUSES",
    loadingState: "DashboardSkeleton",
    errorState: "NOC load error banner",
    i18nLabelKey: "p8.admin.needs_action.open_support",
    rbac: "dashboard.operations | dashboard.moderation",
  },
  {
    id: "noc.needs_action.avatar_review",
    dashboard: "main",
    name: "Avatar review pending",
    api: "GET /api/admin/dashboard",
    responsePath: "noc.needsActionNow[key=avatar_review].count",
    source: "PostgreSQL users.avatar_pending_review=true",
    meaning: "User avatars awaiting moderator review",
    calculation: "COUNT(users) WHERE avatar_pending_review=true",
    loadingState: "DashboardSkeleton",
    errorState: "NOC load error banner",
    i18nLabelKey: "p8.admin.needs_action.avatar_review",
    rbac: "dashboard.operations | dashboard.moderation",
  },
  {
    id: "noc.needs_action.critical_issues",
    dashboard: "main",
    name: "Critical issues",
    api: "GET /api/admin/dashboard",
    responsePath: "noc.needsActionNow[key=critical_issues].count",
    source: "Derived: DB readiness + WS health + abuse spike",
    meaning: "Composite critical signal count (readyz fail, WS unhealthy, report spike ≥8/h)",
    calculation: "Sum of (readyz fail ? 1 : 0) + (ws unhealthy ? 1 : 0) + (reports last hour ≥ 8 ? 1 : 0)",
    loadingState: "DashboardSkeleton",
    errorState: "NOC load error banner",
    i18nLabelKey: "p8.admin.needs_action.critical_issues",
    rbac: "dashboard.operations | dashboard.moderation",
  },
  {
    id: "noc.health.cpu",
    dashboard: "main",
    name: "Host CPU",
    api: "GET /api/admin/dashboard",
    responsePath: "noc.systemHealthGrid[key=cpu]",
    source: "Placeholder — host metrics deferred to P13 (P8-1H)",
    meaning: "VPS CPU not wired on NOC; Monitoring page has load averages",
    calculation: "status=muted, value=null",
    loadingState: "Shows i18n waiting_host_metrics",
    errorState: "N/A — intentional placeholder",
    emptyState: "p8.admin.noc.cpu.waiting_host_metrics",
    i18nLabelKey: "p8.admin.noc.health.cpu",
    rbac: "Founder + system permission (systemHealthGrid hidden for other roles)",
    placeholder: true,
  },
  {
    id: "noc.queue.pending_ads",
    dashboard: "main",
    name: "Queue — pending ads",
    api: "GET /api/admin/dashboard",
    responsePath: "noc.queueCenter[key=pending_ads].count",
    source: "Same as pending ads needs-action",
    meaning: "Pending ads in queue center panel",
    calculation: "COUNT(ads) status=pending",
    loadingState: "DashboardSkeleton",
    errorState: "NOC load error banner",
    i18nLabelKey: "p8.admin.queue.pending_ads",
    rbac: "dashboard.operations | dashboard.moderation",
  },
  {
    id: "noc.activity.recent",
    dashboard: "main",
    name: "Recent activity feed",
    api: "GET /api/admin/dashboard",
    responsePath: "noc.recentActivity[]",
    source: "admin_activity_logs + recent ads/reports/users/support",
    meaning: "Merged timeline of admin actions and user events (max 30, UI shows 8)",
    calculation: "buildRecentActivity() merge sort by createdAt",
    loadingState: "DashboardSkeleton",
    errorState: "NOC load error banner",
    emptyState: "p8.admin.noc.activity.empty",
    i18nLabelKey: "p8.admin.noc.section.activity",
    rbac: "dashboard.operations | dashboard.moderation",
  },
  {
    id: "nav.badge.ads_pending",
    dashboard: "main",
    name: "Nav badge — pending ads",
    api: "GET /api/admin/dashboard (+ nav badges helper)",
    responsePath: "badges.adsPendingReview",
    source: "PostgreSQL ads.status=pending",
    meaning: "Shell nav counter for ads moderation",
    calculation: "Same as pending ads count; fetched once per shell mount",
    loadingState: "Badge hidden until first fetch",
    errorState: "Defaults to 0",
    rbac: "dashboard.operations | dashboard.moderation",
  },
  // ── Analytics — GET /api/admin/analytics?period= ───────────────────────
  {
    id: "analytics.totals.users",
    dashboard: "analytics",
    name: "Total users",
    api: "GET /api/admin/analytics",
    responsePath: "totals.users",
    source: "PostgreSQL COUNT(users)",
    meaning: "All registered users",
    calculation: "COUNT(users) — not period-filtered",
    loadingState: "AdminPageLoading",
    errorState: "AdminErrorState + retry",
    i18nLabelKey: "p8.admin.stats.users_total",
    rbac: "analytics",
  },
  {
    id: "analytics.totals.ads",
    dashboard: "analytics",
    name: "Total ads",
    api: "GET /api/admin/analytics",
    responsePath: "totals.ads",
    source: "PostgreSQL COUNT(ads)",
    meaning: "All ads all statuses",
    calculation: "COUNT(ads)",
    loadingState: "AdminPageLoading",
    errorState: "AdminErrorState + retry",
    i18nLabelKey: "p8.admin.stats.ads_total",
    rbac: "analytics",
  },
  {
    id: "analytics.foundation.report_resolution_rate",
    dashboard: "analytics",
    name: "Report resolution rate %",
    api: "GET /api/admin/analytics",
    responsePath: "analyticsFoundation.reportResolutionRatePct",
    source: "Derived from reports resolved vs open+in_review",
    meaning: "resolved / (resolved + open + in_review) × 100; null when denominator 0",
    calculation: "Math.round(resolved/denom*1000)/10 or null",
    loadingState: "AdminPageLoading",
    errorState: "AdminErrorState + retry",
    emptyState: "Shows em dash when null",
    i18nLabelKey: "p8.admin.stats.report_resolution_rate",
    rbac: "analytics",
  },
  {
    id: "analytics.foundation.support_resolution_rate",
    dashboard: "analytics",
    name: "Support resolution rate %",
    api: "GET /api/admin/analytics",
    responsePath: "analyticsFoundation.supportResolutionRatePct",
    source: "Derived from support resolved+closed vs total tickets",
    meaning: "Percentage of support tickets resolved or closed",
    calculation: "(resolved+closed)/total*100 or null",
    loadingState: "AdminPageLoading",
    errorState: "AdminErrorState + retry",
    emptyState: "Shows em dash when null",
    i18nLabelKey: "p8.admin.stats.support_resolution_rate",
    rbac: "analytics",
  },
  {
    id: "analytics.period_metrics",
    dashboard: "analytics",
    name: "Period metrics bar chart",
    api: "GET /api/admin/analytics?period={today|7d|30d|all}",
    responsePath: "periodMetrics.*",
    source: "PostgreSQL filtered by periodStart",
    meaning: "Users/ads/reports/support/views created within selected period",
    calculation: "COUNT/GROUP queries with gte(created_at, periodStart)",
    loadingState: "AdminPageLoading + opacity while refetching",
    errorState: "AdminErrorState + retry",
    i18nLabelKey: "p8.admin.stats.period_metrics",
    rbac: "analytics",
  },
  // ── Operations — GET /api/admin/operations/founder ─────────────────────
  {
    id: "operations.health.total_open",
    dashboard: "operations",
    name: "Total open queue items",
    api: "GET /api/admin/operations/founder",
    responsePath: "health.totalOpen",
    source: "Sum across verification/reports/support/ads workflow queues",
    meaning: "All open operational items across domains",
    calculation: "getOpsQueueSummary + staff load aggregation",
    loadingState: "AdminPageLoading",
    errorState: "AdminErrorState + retry",
    i18nLabelKey: "p8.admin.operations.metric_open",
    rbac: "Founder only (UI guard)",
  },
  {
    id: "operations.health.total_unassigned",
    dashboard: "operations",
    name: "Total unassigned",
    api: "GET /api/admin/operations/founder",
    responsePath: "health.totalUnassigned",
    source: "Workflow assignment tables per domain",
    meaning: "Open items with no staff assignee",
    calculation: "Sum domain unassigned counts",
    loadingState: "AdminPageLoading",
    errorState: "AdminErrorState + retry",
    i18nLabelKey: "p8.admin.operations.metric_unassigned",
    rbac: "Founder only",
  },
  {
    id: "operations.health.sla_exceeded",
    dashboard: "operations",
    name: "SLA exceeded total",
    api: "GET /api/admin/operations/founder",
    responsePath: "health.totalSlaExceeded",
    source: "SLA fields on workflow entities",
    meaning: "Items past SLA deadline",
    calculation: "slaState='exceeded' counts summed",
    loadingState: "AdminPageLoading",
    errorState: "AdminErrorState + retry",
    i18nLabelKey: "p8.admin.operations.metric_sla_exceeded",
    rbac: "Founder only",
  },
  {
    id: "operations.staff_load",
    dashboard: "operations",
    name: "Staff load table",
    api: "GET /api/admin/operations/founder",
    responsePath: "staffLoad.staff[]",
    source: "admin_staff + per-domain open counts",
    meaning: "Per-staff open items, SLA breaches, load % vs claim limit",
    calculation: "getStaffLoadSnapshot()",
    loadingState: "AdminPageLoading",
    errorState: "AdminErrorState + retry",
    emptyState: "p8.admin.operations.no_staff",
    i18nLabelKey: "p8.admin.operations.staff_load",
    rbac: "Founder only",
  },
  // ── Monitoring — GET /api/admin/monitoring ─────────────────────────────
  {
    id: "monitoring.overall_status",
    dashboard: "monitoring",
    name: "Overall system status",
    api: "GET /api/admin/monitoring",
    responsePath: "snapshot.overallStatus",
    source: "buildAdminMonitoringSnapshot() composite",
    meaning: "ok | warning | critical from alerts + health checks",
    calculation: "Worst severity among component health + founder alerts",
    loadingState: "AdminPageLoading",
    errorState: "AdminErrorState + retry",
    rbac: "Founder + system permission",
  },
  {
    id: "monitoring.server.cpu",
    dashboard: "monitoring",
    name: "CPU cores / load",
    api: "GET /api/admin/monitoring",
    responsePath: "snapshot.serverMetrics.cpu",
    source: "Node os.cpus / loadavg",
    meaning: "Host CPU cores and 1m load average",
    calculation: "os module snapshot at request time",
    loadingState: "AdminPageLoading",
    errorState: "AdminErrorState + retry",
    i18nLabelKey: "p8.admin.monitoring.metric_cpu_cores",
    rbac: "Founder + system",
  },
  {
    id: "monitoring.api.latency_p95",
    dashboard: "monitoring",
    name: "API latency p95",
    api: "GET /api/admin/monitoring",
    responsePath: "snapshot.apiMetrics.latencyMs.p95Ms",
    source: "In-process latency tracker ring buffer",
    meaning: "95th percentile HTTP handler latency since process start/window",
    calculation: "observability latency tracker percentiles",
    loadingState: "AdminPageLoading",
    errorState: "AdminErrorState + retry",
    i18nLabelKey: "p8.admin.monitoring.metric_latency_p95",
    rbac: "Founder + system",
  },
  {
    id: "monitoring.ws.online_users",
    dashboard: "monitoring",
    name: "WebSocket online users",
    api: "GET /api/admin/monitoring",
    responsePath: "snapshot.websocketMetrics.onlineUsers",
    source: "In-memory WebSocket map",
    meaning: "Same semantic as NOC online now — single-instance",
    calculation: "countUsersWithOpenChatSockets()",
    loadingState: "AdminPageLoading",
    errorState: "AdminErrorState + retry",
    i18nLabelKey: "p8.admin.monitoring.metric_ws_online",
    rbac: "Founder + system",
  },
  {
    id: "monitoring.founder.sla_exceeded",
    dashboard: "monitoring",
    name: "Founder SLA exceeded",
    api: "GET /api/admin/monitoring",
    responsePath: "snapshot.founder.slaAlerts.totalSlaExceeded",
    source: "Operations queue SLA aggregation",
    meaning: "Cross-domain SLA breaches for founder view",
    calculation: "Same family as operations.health.totalSlaExceeded",
    loadingState: "AdminPageLoading",
    errorState: "AdminErrorState + retry",
    i18nLabelKey: "p8.admin.monitoring.founder_sla_exceeded",
    rbac: "Founder + system",
  },
  {
    id: "monitoring.notification_feed",
    dashboard: "main",
    name: "Admin notification center feed",
    api: "—",
    responsePath: "—",
    source: "Not implemented",
    meaning: "Architecture contract UI only — no backend feed",
    calculation: "P11 / P15",
    loadingState: "Static foundation cards",
    errorState: "N/A",
    emptyState: "p8.admin.notifications.foundation.channel_pending",
    i18nLabelKey: "p8.admin.notifications.foundation.title",
    rbac: "Founder blocks on dashboard",
    placeholder: true,
  },
  {
    id: "monitoring.roles_staff_summary",
    dashboard: "main",
    name: "Roles panel live staff summary",
    api: "GET /api/admin/staff (optional future wire)",
    responsePath: "—",
    source: "RBAC architecture contract on NOC",
    meaning: "Static role definitions; live staff counts optional P8-1F defer to staff page",
    calculation: "roles-permissions-foundation.tsx static i18n",
    loadingState: "Static",
    errorState: "N/A",
    i18nLabelKey: "p8.admin.roles.foundation.title",
    rbac: "Founder blocks on dashboard",
    placeholder: true,
  },
];

export function getDashboardContract(id: string): DashboardContract | null {
  return DASHBOARD_CONTRACTS.find((c) => c.id === id) ?? null;
}

export function dashboardContractAttrs(id: string): { "data-dashboard-contract": string } {
  return { "data-dashboard-contract": id };
}

export function contractsForDashboard(dashboard: DashboardSurface): DashboardContract[] {
  return DASHBOARD_CONTRACTS.filter((c) => c.dashboard === dashboard);
}
