import dotenv from "dotenv";
import pg from "pg";
import path from "path";
import { fileURLToPath } from "url";
const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.join(__dirname, "..", ".env") });
dotenv.config({ path: path.join(__dirname, "..", ".env.local"), override: true });
const c = new pg.Client({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
await c.connect();
const a = await c.query(`SELECT id, status, views FROM ads WHERE id IN (19, 65)`);
const i = await c.query(`SELECT indexname FROM pg_indexes WHERE tablename='ad_views' AND indexname='ad_views_ad_viewer_unique'`);
console.log(JSON.stringify({ ads: a.rows, hasUnique: i.rows.length > 0 }, null, 2));
await c.end();
