import type { DynamicFieldDef } from "./types";

export const OPT_CONDITION = [
  "جديد",
  "مثل الجديد",
  "جيد جداً",
  "جيد",
  "مقبول",
  "يحتاج صيانة",
] as const;

export const OPT_COLOR = [
  "أسود",
  "أبيض",
  "فضي",
  "ذهبي",
  "أزرق",
  "أحمر",
  "أخضر",
  "بنفسجي",
  "وردي",
  "رمادي",
  "أخرى",
] as const;

export const OPT_YEAR = [
  "2025+",
  "2020-2024",
  "2015-2019",
  "2010-2014",
  "2005-2009",
  "2000-2004",
  "أقدم",
] as const;

export const OPT_MANUFACTURER_PHONE = [
  "Apple",
  "Samsung",
  "Huawei",
  "Xiaomi",
  "Google",
  "OnePlus",
  "Oppo",
  "Honor",
  "Sony",
  "أخرى",
] as const;

export const OPT_MANUFACTURER_LAPTOP = [
  "Apple",
  "Dell",
  "HP",
  "Lenovo",
  "Asus",
  "Acer",
  "MSI",
  "Microsoft",
  "أخرى",
] as const;

export const OPT_CAR_BRAND = [
  "BMW",
  "Mercedes",
  "Audi",
  "Volkswagen",
  "Toyota",
  "Hyundai",
  "Kia",
  "Opel",
  "Ford",
  "Renault",
  "Peugeot",
  "Skoda",
  "أخرى",
] as const;

export const OPT_STORAGE_PHONE = [
  "16GB",
  "32GB",
  "64GB",
  "128GB",
  "256GB",
  "512GB",
  "1TB",
  "أخرى",
] as const;

export const OPT_RAM = ["4GB", "8GB", "16GB", "32GB", "64GB", "أخرى"] as const;

export const OPT_AREA = [
  "أقل من 50 م²",
  "50-80 م²",
  "80-120 م²",
  "120-180 م²",
  "أكثر من 180 م²",
] as const;

export const OPT_ROOMS = ["استوديو", "1", "2", "3", "4", "5+"] as const;

/** Catalog: single definition per field id — SSOT for labels and base options */
export const FIELD_CATALOG: Record<string, DynamicFieldDef> = {
  manufacturer: {
    id: "manufacturer",
    label: "الشركة المصنعة",
    type: "select",
    options: [...OPT_MANUFACTURER_PHONE],
  },
  manufacturer_laptop: {
    id: "manufacturer",
    label: "الشركة المصنعة",
    type: "select",
    options: [...OPT_MANUFACTURER_LAPTOP],
  },
  model: {
    id: "model",
    label: "الموديل",
    type: "select",
    dependsOn: "manufacturer",
    optionsMapKey: "phone_models",
    options: ["أخرى"],
  },
  model_laptop: {
    id: "model",
    label: "الموديل",
    type: "select",
    dependsOn: "manufacturer",
    optionsMapKey: "laptop_models",
    options: ["أخرى"],
  },
  generic_model: {
    id: "model",
    label: "الموديل",
    type: "select",
    options: ["قياسي", "برو", "إصدار خاص", "أخرى"],
  },
  condition: {
    id: "condition",
    label: "الحالة",
    type: "select",
    options: [...OPT_CONDITION],
  },
  color: {
    id: "color",
    label: "اللون",
    type: "select",
    options: [...OPT_COLOR],
  },
  storage: {
    id: "storage",
    label: "السعة التخزينية",
    type: "select",
    options: [...OPT_STORAGE_PHONE],
  },
  accessories: {
    id: "accessories",
    label: "الملحقات",
    type: "select",
    options: [
      "الجهاز فقط",
      "مع الشاحن",
      "مع العلبة",
      "مع الشاحن والعلبة",
      "مع سماعات",
      "كامل الملحقات",
    ],
  },
  connectivity: {
    id: "connectivity",
    label: "الاتصال",
    type: "select",
    options: ["WiFi فقط", "WiFi + LTE", "WiFi + 5G"],
  },
  ram: {
    id: "ram",
    label: "الرام",
    type: "select",
    options: [...OPT_RAM],
  },
  cpu: {
    id: "cpu",
    label: "المعالج",
    type: "select",
    options: ["Intel i3", "Intel i5", "Intel i7", "Intel i9", "AMD Ryzen 5", "AMD Ryzen 7", "Apple M1", "Apple M2", "Apple M3", "أخرى"],
  },
  gpu: {
    id: "gpu",
    label: "كرت الشاشة",
    type: "select",
    options: ["مدمج", "NVIDIA GTX", "NVIDIA RTX", "AMD Radeon", "أخرى"],
  },
  screen_size: {
    id: "screen_size",
    label: "حجم الشاشة",
    type: "select",
    options: ["أقل من 24\"", "24-32\"", "33-43\"", "44-55\"", "56-65\"", "أكثر من 65\""],
  },
  resolution: {
    id: "resolution",
    label: "الدقة",
    type: "select",
    options: ["HD", "Full HD", "2K", "4K", "8K"],
  },
  refresh_rate: {
    id: "refresh_rate",
    label: "معدل التحديث",
    type: "select",
    options: ["60Hz", "75Hz", "120Hz", "144Hz", "165Hz+", "أخرى"],
  },
  smart_tv: {
    id: "smart_tv",
    label: "تلفزيون ذكي",
    type: "select",
    options: ["نعم", "لا"],
  },
  platform: {
    id: "platform",
    label: "المنصة",
    type: "select",
    options: ["PlayStation", "Xbox", "Nintendo Switch", "PC", "أخرى"],
  },
  sensor_type: {
    id: "sensor_type",
    label: "نوع الكاميرا",
    type: "select",
    options: ["رقمية", "DSLR", "Mirrorless", "Action Cam", "أخرى"],
  },
  headphone_type: {
    id: "headphone_type",
    label: "النوع",
    type: "select",
    options: ["داخل الأذن", "فوق الأذن", "لاسلكي", "أخرى"],
  },
  wifi_standard: {
    id: "wifi_standard",
    label: "معيار WiFi",
    type: "select",
    options: ["WiFi 5", "WiFi 6", "WiFi 6E", "WiFi 7"],
  },
  printer_type: {
    id: "printer_type",
    label: "نوع الطابعة",
    type: "select",
    options: ["ليزر", "حبر", "متعددة الوظائف", "أخرى"],
  },
  printer_color: {
    id: "printer_color",
    label: "طباعة ملونة",
    type: "select",
    options: ["ملونة", "أبيض وأسود"],
  },
  accessory_type: {
    id: "accessory_type",
    label: "نوع الإكسسوار",
    type: "select",
    options: ["غطاء", "كيبورد", "ماوس", "حامل", "أخرى"],
  },
  compatibility: {
    id: "compatibility",
    label: "التوافق",
    type: "select",
    options: ["iPhone", "Samsung", "USB-C", "عام", "أخرى"],
  },
  appliance_type: {
    id: "appliance_type",
    label: "نوع الجهاز",
    type: "select",
    options: ["ثلاجة", "غسالة", "مكيف", "ميكروويف", "مكنسة", "ماكينة قهوة", "أخرى"],
  },
  car_brand: {
    id: "car_brand",
    label: "ماركة السيارة",
    type: "select",
    options: [...OPT_CAR_BRAND],
  },
  car_model: {
    id: "car_model",
    label: "الموديل",
    type: "select",
    dependsOn: "car_brand",
    optionsMapKey: "car_models",
    options: ["أخرى"],
  },
  year: {
    id: "year",
    label: "سنة الصنع",
    type: "select",
    options: [...OPT_YEAR],
  },
  mileage: {
    id: "mileage",
    label: "الكيلومترات",
    type: "select",
    options: [
      "أقل من 50,000",
      "50,000 - 100,000",
      "100,000 - 150,000",
      "150,000 - 200,000",
      "200,000+",
    ],
  },
  fuel: {
    id: "fuel",
    label: "نوع الوقود",
    type: "select",
    options: ["بنزين", "ديزل", "كهرباء", "هايبرد", "غاز", "أخرى"],
  },
  transmission: {
    id: "transmission",
    label: "ناقل الحركة",
    type: "select",
    options: ["أوتوماتيك", "يدوي", "نصف أوتوماتيك"],
  },
  engine_cc: {
    id: "engine_cc",
    label: "سعة المحرك",
    type: "select",
    options: ["أقل من 125cc", "125-250cc", "250-500cc", "500cc+"],
  },
  bike_type: {
    id: "bike_type",
    label: "نوع الدراجة",
    type: "select",
    options: ["مدينة", "جبلية", "طريق", "أطفال", "أخرى"],
  },
  frame_size: {
    id: "frame_size",
    label: "المقاس",
    type: "select",
    options: ["S", "M", "L", "XL", "أخرى"],
  },
  scooter_type: {
    id: "scooter_type",
    label: "النوع",
    type: "select",
    options: ["كهربائي", "بنزين", "أخرى"],
  },
  range_km: {
    id: "range_km",
    label: "المدى",
    type: "select",
    options: ["أقل من 30 كم", "30-60 كم", "60-100 كم", "100+ كم"],
  },
  part_type: {
    id: "part_type",
    label: "نوع القطعة",
    type: "select",
    options: ["محرك", "فرامل", "إطارات", "بطارية", "زيوت", "أخرى"],
  },
  compatible_brand: {
    id: "compatible_brand",
    label: "ماركة متوافقة",
    type: "select",
    options: [...OPT_CAR_BRAND],
  },
  tire_size: {
    id: "tire_size",
    label: "مقاس الإطار",
    type: "select",
    options: ["13\"", "14\"", "15\"", "16\"", "17\"", "18\"", "19\"", "20\"+", "أخرى"],
  },
  season: {
    id: "season",
    label: "الموسم",
    type: "select",
    options: ["صيفي", "شتوي", "لكل المواسم"],
  },
  quantity: {
    id: "quantity",
    label: "الكمية",
    type: "select",
    options: ["1", "2", "3", "4+"],
  },
  area: {
    id: "area",
    label: "المساحة",
    type: "select",
    options: [...OPT_AREA],
  },
  rooms: {
    id: "rooms",
    label: "عدد الغرف",
    type: "select",
    options: [...OPT_ROOMS],
  },
  bathrooms: {
    id: "bathrooms",
    label: "الحمامات",
    type: "select",
    options: ["1", "2", "3+"],
  },
  floor: {
    id: "floor",
    label: "الطابق",
    type: "select",
    options: ["أرضي", "1", "2", "3", "4+", "علوي"],
  },
  furnished: {
    id: "furnished",
    label: "مفروش",
    type: "select",
    options: ["نعم", "لا", "جزئياً"],
  },
  heating: {
    id: "heating",
    label: "التدفئة",
    type: "select",
    options: ["مركزي", "تدفئة أرضية", "كهرباء", "غاز", "أخرى"],
  },
  plot_area: {
    id: "plot_area",
    label: "مساحة الأرض",
    type: "select",
    options: ["أقل من 200 م²", "200-500 م²", "500-1000 م²", "1000+ م²"],
  },
  floors_count: {
    id: "floors_count",
    label: "عدد الطوابق",
    type: "select",
    options: ["1", "2", "3", "4+"],
  },
  garden: {
    id: "garden",
    label: "حديقة",
    type: "select",
    options: ["نعم", "لا"],
  },
  available_from: {
    id: "available_from",
    label: "متاح من",
    type: "select",
    options: ["فوراً", "خلال شهر", "تاريخ محدد"],
  },
  commercial_type: {
    id: "commercial_type",
    label: "نوع المحل",
    type: "select",
    options: ["مطعم", "مقهى", "مكتب", "محل تجاري", "مستودع", "أخرى"],
  },
  zoning: {
    id: "zoning",
    label: "التصنيف",
    type: "select",
    options: ["سكني", "تجاري", "زراعي", "مختلط"],
  },
  furniture_type: {
    id: "furniture_type",
    label: "نوع الأثاث",
    type: "select",
    options: ["سرير", "خزانة", "كنب", "طاولة", "كرسي", "مكتب", "أخرى"],
  },
  material: {
    id: "material",
    label: "المادة",
    type: "select",
    options: ["خشب", "معدن", "بلاستيك", "زجاج", "مختلط", "أخرى"],
  },
  kitchen_item_type: {
    id: "kitchen_item_type",
    label: "نوع الأداة",
    type: "select",
    options: ["أواني", "سكاكين", "أجهزة صغيرة", "طقم كامل", "أخرى"],
  },
  equipment_type: {
    id: "equipment_type",
    label: "نوع المعدة",
    type: "select",
    options: ["فرن", "ثلاجة عرض", "ماكينة قهوة", "محضرة", "طاولة عمل", "أخرى"],
  },
  equipment_brand: {
    id: "equipment_brand",
    label: "العلامة التجارية",
    type: "select",
    options: [
      "Bosch",
      "Siemens",
      "Rational",
      "Hobart",
      "Electrolux",
      "Miele",
      "DeLonghi",
      "محلي",
      "أخرى",
    ],
  },
  power: {
    id: "power",
    label: "الطاقة",
    type: "select",
    options: ["كهرباء 220V", "غاز", "مختلط", "غير محدد"],
  },
  decor_type: {
    id: "decor_type",
    label: "نوع الديكور",
    type: "select",
    options: ["لوحة", "سجاد", "مصباح", "مرآة", "أخرى"],
  },
  tool_type: {
    id: "tool_type",
    label: "نوع الأداة",
    type: "select",
    options: ["تنظيف", "DIY", "كهربائية منزلية", "أخرى"],
  },
  health_item_type: {
    id: "health_item_type",
    label: "نوع المنتج",
    type: "select",
    options: ["كرسي متحرك", "مشاية", "سرير طبي", "جهاز قياس", "أخرى"],
  },
  garden_item_type: {
    id: "garden_item_type",
    label: "النوع",
    type: "select",
    options: ["نبات", "أثاث حديقة", "شواية", "أدوات", "أخرى"],
  },
  clothing_size: {
    id: "clothing_size",
    label: "المقاس",
    type: "select",
    options: ["XS", "S", "M", "L", "XL", "XXL", "أخرى"],
  },
  shoe_size: {
    id: "shoe_size",
    label: "مقاس الحذاء",
    type: "select",
    options: ["36", "37", "38", "39", "40", "41", "42", "43", "44", "45+"],
  },
  gender: {
    id: "gender",
    label: "الجنس",
    type: "select",
    options: ["رجالي", "نسائي", "أطفال", "للجميع"],
  },
  brand: {
    id: "brand",
    label: "العلامة",
    type: "select",
    options: ["بدون علامة", "محلي", "ماركة معروفة", "أخرى"],
  },
  jewelry_material: {
    id: "jewelry_material",
    label: "المادة",
    type: "select",
    options: ["ذهب", "فضة", "ألماس", "مختلط", "أخرى"],
  },
  beauty_type: {
    id: "beauty_type",
    label: "النوع",
    type: "select",
    options: ["عطر", "مكياج", "عناية بالبشرة", "عناية بالشعر"],
  },
  volume: {
    id: "volume",
    label: "الحجم",
    type: "select",
    options: ["أقل من 50ml", "50-100ml", "100ml+", "غير محدد"],
  },
  sealed: {
    id: "sealed",
    label: "مغلق",
    type: "select",
    options: ["نعم", "لا"],
  },
  age_range: {
    id: "age_range",
    label: "الفئة العمرية",
    type: "select",
    options: ["0-6 أشهر", "6-12 شهر", "1-3 سنوات", "3-6 سنوات", "6+ سنوات"],
  },
  baby_item_type: {
    id: "baby_item_type",
    label: "النوع",
    type: "select",
    options: ["سرير", "كرسي سيارة", "حفاضات", "رضاعة", "أخرى"],
  },
  pet_breed: {
    id: "pet_breed",
    label: "السلالة",
    type: "select",
    options: ["مختلط", "أصيل", "غير محدد"],
  },
  pet_age: {
    id: "pet_age",
    label: "العمر",
    type: "select",
    options: ["صغير", "بالغ", "كبير"],
  },
  pet_gender: {
    id: "pet_gender",
    label: "الجنس",
    type: "select",
    options: ["ذكر", "أنثى", "غير محدد"],
  },
  vaccinated: {
    id: "vaccinated",
    label: "مُطعّم",
    type: "select",
    options: ["نعم", "لا", "غير محدد"],
  },
  animal_type: {
    id: "animal_type",
    label: "نوع الحيوان",
    type: "select",
    options: ["كلب", "قط", "طائر", "سمك", "أخرى"],
  },
  sport_type: {
    id: "sport_type",
    label: "نوع الرياضة",
    type: "select",
    options: ["لياقة", "كرة", "جري", "صيد", "أخرى"],
  },
  photo_accessory_type: {
    id: "photo_accessory_type",
    label: "نوع الملحق",
    type: "select",
    options: ["حامل", "إضاءة", "حقيبة", "عدسة", "أخرى"],
  },
  players: {
    id: "players",
    label: "عدد اللاعبين",
    type: "select",
    options: ["1", "2", "2-4", "4+", "جماعي"],
  },
  gear_type: {
    id: "gear_type",
    label: "نوع المعدات",
    type: "select",
    options: ["خيمة", "كيس نوم", "حقيبة", "أخرى"],
  },
  capacity: {
    id: "capacity",
    label: "السعة",
    type: "select",
    options: ["1 شخص", "2 أشخاص", "3-4", "4+"],
  },
  hobby_type: {
    id: "hobby_type",
    label: "نوع الهواية",
    type: "select",
    options: ["خياطة", "رسم", "صناعة يدوية", "أخرى"],
  },
  shisha_item_type: {
    id: "shisha_item_type",
    label: "النوع",
    type: "select",
    options: ["أراجيل كاملة", "رأس شيشة", "خرطوم", "فحم", "معسل", "أخرى"],
  },
  language: {
    id: "language",
    label: "اللغة",
    type: "select",
    options: ["عربي", "ألماني", "إنجليزي", "أخرى"],
  },
  format: {
    id: "format",
    label: "الصيغة",
    type: "select",
    options: ["ورقي", "رقمي", "CD", "فينيل", "DVD/Blu-ray"],
  },
  instrument_type: {
    id: "instrument_type",
    label: "نوع الآلة",
    type: "select",
    options: ["جيتار", "بيانو", "كمان", "طبول", "أخرى"],
  },
  event_date: {
    id: "event_date",
    label: "تاريخ الفعالية",
    type: "select",
    options: ["هذا الأسبوع", "هذا الشهر", "لاحقاً"],
  },
  venue: {
    id: "venue",
    label: "المكان",
    type: "select",
    options: ["داخلي", "خارجي", "مسرح", "ملعب", "أخرى"],
  },
  service_area: {
    id: "service_area",
    label: "نطاق الخدمة",
    type: "select",
    options: ["مدينتي", "عدة مدن", "كل ألمانيا"],
  },
  availability: {
    id: "availability",
    label: "التوفر",
    type: "select",
    options: ["فوري", "خلال أسبوع", "بموعد"],
  },
  industry: {
    id: "industry",
    label: "المجال",
    type: "select",
    options: ["تقنية", "مطاعم", "بناء", "تعليم", "صحة", "لوجستيات", "أخرى"],
  },
  experience: {
    id: "experience",
    label: "الخبرة",
    type: "select",
    options: ["بدون خبرة", "1-2 سنوات", "3-5 سنوات", "5+ سنوات"],
  },
  lesson_level: {
    id: "lesson_level",
    label: "المستوى",
    type: "select",
    options: ["مبتدئ", "متوسط", "متقدم"],
  },
  lesson_format: {
    id: "lesson_format",
    label: "الشكل",
    type: "select",
    options: ["حضوري", "أونلاين", "مختلط"],
  },
  radius_km: {
    id: "radius_km",
    label: "نطاق المساعدة",
    type: "select",
    options: ["5 كم", "10 كم", "20 كم", "أكثر"],
  },
};

export function catalogField(id: string): DynamicFieldDef {
  const f = FIELD_CATALOG[id];
  if (!f) throw new Error(`Unknown field catalog id: ${id}`);
  return { ...f };
}
